_commit: cb1abb7
_src_path: gh:bswck/skeleton
author_username: bswck
docs: true
email_address: bswck.dev@gmail.com
github_username: bswck
license_name: MIT
org_full_name: Bartosz Sławecki
package_name: configzen
project_description: An advanced configuration library for Python.
publish_on_pypi: true
pypi_project_description: An advanced configuration library for Python.
pypi_project_name: configzen
python_version: '3.8'
repo_name: configzen
test_suite: true
use_precommit: true
visibility: public
