_commit: 0.0.2rc-218-g8123b8a
_src_path: gh:skeleton-ci/skeleton-python
author: bswck
cli: false
copyright: Bartosz Sławecki
description: Manage configuration with pydantic.
docs: true
email: bartoszpiotrslawecki@gmail.com
github: bswck
license: GPL-3.0
package: configzen
precommit: true
pypi: true
pypi_description: Manage configuration with pydantic.
pypi_project: configzen
pypy: true
python: '3.8'
python_until: ''
repo: configzen
rtd: configzen
tests: true
tidelift: true
visibility: public
wip: false
