_commit: 0.0.2rc-161-g1ae7659
_src_path: gh:bswck/skeleton
author: bswck
cli: false
copyright: Bartosz Sławecki
description: Manage configuration with pydantic.
docs: true
email: bswck.dev@gmail.com
github: bswck
license: GPL-3.0
package: configzen
precommit: true
pypi: true
pypi_description: Manage configuration with pydantic.
pypi_project: configzen
pypy: true
python: '3.8'
python_until: '4.0'
repo: configzen
rtd: configzen
tests: true
visibility: public
wip: false
