#!/usr/bin/env bash 
# (C) bswck
#
# Usage:
# $ ./install && poetry shell
poetry install --all-extras

if [ $? -eq 0 ]; then
    echo "Successfully installed dependencies."
else
    echo "Failed to install dependencies."
    exit 1
fi

PYTHON_VERSION="$(cat .python-version)"

poetry env use $PYTHON_VERSION -q

if [ $? -eq 0 ]; then
    echo "Successfully set Python version to $PYTHON_VERSION."
else
    echo "Failed to set Python version to $PYTHON_VERSION."
    exit 1
fi

DIR="$(dirname "$(readlink -f "$0")")"
CMD="export PATH=\$PATH:$DIR/scripts"
APPEND="\n# Add repo scripts to PATH for convenience.\n$CMD\n"
ACTIVATE="$(poetry env info -p)/bin/activate"

echo $APPEND >> $ACTIVATE
