site_name: configzen
repo_url: https://github.com/bswck/configzen
repo_name: bswck/configzen
copyright: Copyright &copy; 2023 bswck
nav:
- Home: index.md
- API Reference:
  - 'configzen.model': 'api/model.md'
  - 'configzen.decorators': 'api/decorators.md'
  - 'configzen.errors': 'api/errors.md'
  - 'configzen.field': 'api/field.md'
  - 'configzen.interpolation': 'api/interpolation.md'
  - 'configzen.processor': 'api/processor.md'
  - 'configzen.route': 'api/route.md'
#- Examples: examples.md
theme:
  name: material
  palette:

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: pink
    accent: pink
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: pink
    accent: pink
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to light mode
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
markdown_extensions:
- admonition
- footnotes
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
