#!/usr/bin/env bash
# (C) bswck
# A manual alias for long poetry commands ✨
#
# Run this before pushing to ensure that package locks are up-to-date.
# We update requirements-dev.txt in order to make sure that the CI environment
# can install the dev dependencies without Poetry.
#
# Usage:
# $ lock
echo "✨ Doing the magic ✨"
poetry lock
poetry export --without=dev -f requirements.txt -o requirements.txt
poetry export --with=dev --extras=all -f requirements.txt -o requirements-dev.txt