name: Lint (black --check, pylint, ruff)

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install $(cat requirements-dev.txt | grep -oiP "(pylint|black|ruff)\\s?==\\s?(([0-9]+\\.){2}[0-9]+)")
    - name: Check with black
      run: >-
        black --check configzen/
    - name: Analyse the code with pylint
      run: >-
        pylint configzen/ --fail-under=9
    - name: Analyse the code with ruff
      run: >-
        ruff configzen/
