# Modified from https://github.com/mypyc/mypy_mypyc-wheels/blob/master/.github/workflows/build.yml

name: Publish

on:
  workflow_dispatch:
  release:
    types: [ published ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: py${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ 39, 310, 311 ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all
    - uses: pypa/cibuildwheel@v2.11.1
      env:
        CIBW_BUILD: "cp${{ matrix.python-version}}-*"

    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ./wheelhouse/*.whl

  build_sdist_python_wheel:
    name: sdist and python wheel
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      name: Install Python
      with:
        python-version: "3.8"
    - name: Build Sdist
      run: |
        pip install build
        python -m build --sdist
    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: |
          dist/*.tar.gz

  release:
    name: create release
    needs: [ build_wheels, build_sdist_python_wheel ]
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: publish
      run: |
        pip install twine
        twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}
